version: "3.8"

services:
  frontend:
    image: pecs-frontend
    restart: always
    networks:
      - traefik-public
      - default
    build:
      context: ./
      args:
        - VITE_API_URL=https://api-pecs-backend.speats.ch
        - NODE_ENV=production
    ports:
      - "5174:5174"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.services.pecs-frontend.loadbalancer.server.port=80
      - traefik.http.routers.pecs-frontend-http.rule=Host(`dashboard-pecs.speats.ch`)
      - traefik.http.routers.pecs-frontend-http.entrypoints=http
      - traefik.http.routers.pecs-frontend-https.rule=Host(`dashboard-pecs.speats.ch`)
      - traefik.http.routers.pecs-frontend-https.entrypoints=https
      - traefik.http.routers.pecs-frontend-https.tls=true
      - traefik.http.routers.pecs-frontend-https.tls.certresolver=le
      # Enable redirection for HTTP and HTTPS
      - traefik.http.routers.pecs-frontend-http.middlewares=https-redirect

networks:
  traefik-public:
    external: true
