<<<<<<< HEAD
version: "3.8"
services:
  frontend-pecs:
    image: pecs-frontend
    container_name: frontend-pecs
    restart: always
    networks:
      - traefik-public
      - default
=======
version: '3.8'

services:
  frontend:
>>>>>>> 777161ae2beea8db5ffb57ed4d5d12733cf7e6d2
    build:
      context: ./
      args:
        - VITE_API_URL=https://api-pecs-backend.speats.ch
        - NODE_ENV=production
    ports:
      - "5174:5174"
<<<<<<< HEAD
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.services.frontend-pecs.loadbalancer.server.port=5174
      - traefik.http.routers.frontend-pecs-http.rule=Host(`dashboard-pecs.speats.ch`)
      - traefik.http.routers.frontend-pecs-http.entrypoints=http
      - traefik.http.routers.frontend-pecs-https.rule=Host(`dashboard-pecs.speats.ch`)
      - traefik.http.routers.frontend-pecs-https.entrypoints=https
      - traefik.http.routers.frontend-pecs-https.tls=true
      - traefik.http.routers.frontend-pecs-https.tls.certresolver=le
      - traefik.http.routers.frontend-pecs-http.middlewares=https-redirect

networks:
  traefik-public:
    external: true
  default:
    driver: bridge
=======
    restart: always
    networks:
      - default
>>>>>>> 777161ae2beea8db5ffb57ed4d5d12733cf7e6d2
