version: '3.8'

services:
  frontend:
    build:
      context: ./
      args:
        - VITE_API_URL=https://api-pecs-backend.speats.ch
        - NODE_ENV=production
    ports:
      - "5174:5174"
    restart: always
    networks:
      - default