/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutSequencesImport } from './routes/_layout/sequences'
import { Route as LayoutPhrasesImport } from './routes/_layout/phrases'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutGroupSequencesImport } from './routes/_layout/group-sequences'
import { Route as LayoutCustomPecsImport } from './routes/_layout/custom-pecs'
import { Route as LayoutCollectionsImport } from './routes/_layout/collections'
import { Route as LayoutCategoryPictogramsImport } from './routes/_layout/category-pictograms'
import { Route as LayoutCategoriesByLanguageImport } from './routes/_layout/categories-by-language'
import { Route as LayoutCategoriesImport } from './routes/_layout/categories'
import { Route as LayoutAdminImport } from './routes/_layout/admin'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSequencesRoute = LayoutSequencesImport.update({
  path: '/sequences',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPhrasesRoute = LayoutPhrasesImport.update({
  path: '/phrases',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGroupSequencesRoute = LayoutGroupSequencesImport.update({
  path: '/group-sequences',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCustomPecsRoute = LayoutCustomPecsImport.update({
  path: '/custom-pecs',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCollectionsRoute = LayoutCollectionsImport.update({
  path: '/collections',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCategoryPictogramsRoute = LayoutCategoryPictogramsImport.update({
  path: '/category-pictograms',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCategoriesByLanguageRoute = LayoutCategoriesByLanguageImport.update(
  {
    path: '/categories-by-language',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutCategoriesRoute = LayoutCategoriesImport.update({
  path: '/categories',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/categories': {
      preLoaderRoute: typeof LayoutCategoriesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/categories-by-language': {
      preLoaderRoute: typeof LayoutCategoriesByLanguageImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/category-pictograms': {
      preLoaderRoute: typeof LayoutCategoryPictogramsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/collections': {
      preLoaderRoute: typeof LayoutCollectionsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/custom-pecs': {
      preLoaderRoute: typeof LayoutCustomPecsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/group-sequences': {
      preLoaderRoute: typeof LayoutGroupSequencesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/phrases': {
      preLoaderRoute: typeof LayoutPhrasesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/sequences': {
      preLoaderRoute: typeof LayoutSequencesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutCategoriesRoute,
    LayoutCategoriesByLanguageRoute,
    LayoutCategoryPictogramsRoute,
    LayoutCollectionsRoute,
    LayoutCustomPecsRoute,
    LayoutGroupSequencesRoute,
    LayoutItemsRoute,
    LayoutPhrasesRoute,
    LayoutSequencesRoute,
    LayoutSettingsRoute,
    LayoutIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
])

/* prettier-ignore-end */
